import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

const CreatePostWizard = () => {
  const {user} = useUser();

  if (!user) return null;

  return (
    <div className="flex gap-3">
      <img 
        src={user.profileImageUrl} 
        alt="Profile Image" 
        className="w-12 h-12 rounded-full" 
      />
      <input placeholder="Tell your story through emojis!" className="grow bg-transparent outline-none"/>

    </div>
  );

}

const Home: NextPage = () => {

  const user = useUser();

  const { data, isLoading } = api.post.getAll.useQuery();  

  if (isLoading) return <div>Loading...</div>

  if (!data) return <div>Something went wrong</div>

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className ="w-full md:max-w-2xl bg-slate-800 border-x border-slate-500">
          <div className="flex border-b border-slate-500 p-4">
            {!user.isSignedIn && (
            <div className="flex justify-center">
              <SignInButton />
            </div>
            )}
            {user.isSignedIn && <CreatePostWizard />}
          </div>
          <div className="flex flex-col">
            {[...data, ...data]?.map((post) => (
              <div key={post.id} className="p-8 border-b border-slate-500"> {post.content} </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;